#!/bin/bash

echo "🚀 TSH Admin Dashboard - iPhone Deployment Guide"
echo "==============================================="

echo ""
echo "📱 Your iPhone is connected and detected as: home (00008130-0004310C1ABA001C)"
echo "✅ iOS Deployment target has been fixed to iOS 12.0"
echo ""

echo "🔧 To deploy to your iPhone, please follow these steps:"
echo ""
echo "1️⃣  OPEN XCODE:"
echo "   • Xcode is already open with your project"
echo "   • Or run: open ios/Runner.xcworkspace"
echo ""
echo "2️⃣  CONFIGURE CODE SIGNING:"
echo "   • Select 'Runner' in the left sidebar"
echo "   • Go to 'Signing & Capabilities' tab"
echo "   • Check ✅ 'Automatically manage signing'"
echo "   • Select your Team (Apple ID): 38U844SAJ5"
echo "   • Bundle ID: com.tsh.admin.tshAdminDashboard"
echo ""
echo "3️⃣  SELECT YOUR IPHONE:"
echo "   • In Xcode device dropdown, select 'home' (your iPhone)"
echo ""
echo "4️⃣  BUILD AND RUN:"
echo "   • Press Cmd+R or click the Play ▶️ button"
echo "   • First build will take a few minutes"
echo ""
echo "5️⃣  TRUST DEVELOPER ON IPHONE:"
echo "   • After installation, go to iPhone Settings"
echo "   • Settings > General > VPN & Device Management"
echo "   • Find your developer profile and tap 'Trust'"
echo ""
echo "🎉 Your TSH Admin Dashboard should then launch on your iPhone!"
echo ""
echo "Alternative: Try Flutter command (may still have signing issues):"
echo "flutter run -d 00008130-0004310C1ABA001C"
