name: TSHSecurityConsole
options:
  bundleIdPrefix: com.tsh
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: 38U844SAJ5
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
    INFOPLIST_KEY_NSCameraUsageDescription: "TSH Security Console needs camera access to scan QR codes for quick approval"
    INFOPLIST_KEY_NSFaceIDUsageDescription: "TSH Security Console uses Face ID for secure authentication"
    GENERATE_INFOPLIST_FILE: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"

targets:
  TSHSecurityConsole:
    type: application
    platform: iOS
    sources:
      - path: TSHSecurityConsole
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tsh.securityconsole
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        ENABLE_PREVIEWS: YES
    entitlements:
      path: TSHSecurityConsole/TSHSecurityConsole.entitlements
      properties:
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.tsh.securityconsole

schemes:
  TSHSecurityConsole:
    build:
      targets:
        TSHSecurityConsole: all
    run:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release
