"""add_product_multilang_and_media_fields

Revision ID: 6163f7adfc75
Revises: 8b5fc7e6bb8a
Create Date: 2025-07-02 21:02:51.912979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6163f7adfc75'
down_revision = '8b5fc7e6bb8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_ar', sa.String(length=100), nullable=True))
    op.add_column('categories', sa.Column('description_ar', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('name_ar', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('description_ar', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('videos', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('products', sa.Column('dimensions', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('size', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('is_digital', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('meta_title', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('tags', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_products_name_ar'), 'products', ['name_ar'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name_ar'), table_name='products')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'meta_description')
    op.drop_column('products', 'meta_title')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'is_digital')
    op.drop_column('products', 'model')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'size')
    op.drop_column('products', 'color')
    op.drop_column('products', 'dimensions')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'videos')
    op.drop_column('products', 'images')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'description_ar')
    op.drop_column('products', 'name_ar')
    op.drop_column('categories', 'description_ar')
    op.drop_column('categories', 'name_ar')
    # ### end Alembic commands ### 