"""Update existing models for enhanced security and multi-tenancy

Revision ID: 7f4232a6ba23
Revises: 6f31f5b15936
Create Date: 2025-08-14 14:09:45.515165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4232a6ba23'
down_revision = '6f31f5b15936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_performance_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('current_rank', sa.Enum('SILVER', 'GOLD', 'DIAMOND', name='performancerank'), nullable=False),
    sa.Column('previous_rank', sa.Enum('SILVER', 'GOLD', 'DIAMOND', name='performancerank'), nullable=True),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('target_achievement_percentage', sa.Float(), nullable=True),
    sa.Column('customer_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('monthly_kpi_score', sa.Float(), nullable=True),
    sa.Column('quarterly_kpi_score', sa.Float(), nullable=True),
    sa.Column('annual_kpi_score', sa.Float(), nullable=True),
    sa.Column('ranking_month', sa.Integer(), nullable=False),
    sa.Column('ranking_year', sa.Integer(), nullable=False),
    sa.Column('rank_bonus_amount', sa.Float(), nullable=True),
    sa.Column('rank_bonus_percentage', sa.Float(), nullable=True),
    sa.Column('special_incentives', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('promotion_notes', sa.Text(), nullable=True),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_performance_rankings_id'), 'employee_performance_rankings', ['id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('CONTRACT', 'ID_COPY', 'PASSPORT_COPY', 'CERTIFICATE', 'MEDICAL_REPORT', 'PERFORMANCE_DOCUMENT', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('title_ar', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_documents_id'), 'employee_documents', ['id'], unique=False)
    op.create_table('hr_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ar', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('message_ar', sa.Text(), nullable=False),
    sa.Column('message_en', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('send_to_all', sa.Boolean(), nullable=True),
    sa.Column('send_push', sa.Boolean(), nullable=True),
    sa.Column('send_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('send_email', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_notifications_id'), 'hr_notifications', ['id'], unique=False)
    op.create_table('payslip_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_record_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payslip_number', sa.String(length=50), nullable=False),
    sa.Column('payslip_content_ar', sa.Text(), nullable=False),
    sa.Column('payslip_content_en', sa.Text(), nullable=False),
    sa.Column('pdf_file_ar_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_file_en_url', sa.String(length=500), nullable=True),
    sa.Column('sent_via_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('sent_via_email', sa.Boolean(), nullable=True),
    sa.Column('employee_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payslip_number')
    )
    op.create_index(op.f('ix_payslip_records_id'), 'payslip_records', ['id'], unique=False)
    op.create_table('whatsapp_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('attachment_urls', sa.Text(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('payslip_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslip_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_integrations_id'), 'whatsapp_integrations', ['id'], unique=False)
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'roles', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_tenant_settings_id'), 'tenant_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_tenant_settings_id'), table_name='tenant_settings')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'tenant_id')
    op.drop_column('roles', 'description')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.drop_index(op.f('ix_whatsapp_integrations_id'), table_name='whatsapp_integrations')
    op.drop_table('whatsapp_integrations')
    op.drop_index(op.f('ix_payslip_records_id'), table_name='payslip_records')
    op.drop_table('payslip_records')
    op.drop_index(op.f('ix_hr_notifications_id'), table_name='hr_notifications')
    op.drop_table('hr_notifications')
    op.drop_index(op.f('ix_employee_documents_id'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_employee_performance_rankings_id'), table_name='employee_performance_rankings')
    op.drop_table('employee_performance_rankings')
    # ### end Alembic commands ### 