"""add_rls_record_level_security_tables

Revision ID: 8579948f044e
Revises: 4c129201dab2
Create Date: 2025-10-21 15:25:54.334293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8579948f044e'
down_revision = '4c129201dab2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('access_granted', sa.Boolean(), nullable=False),
    sa.Column('denial_reason', sa.String(length=500), nullable=True),
    sa.Column('scope_filter_applied', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_access_logs_id'), 'data_access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_data_access_logs_resource_type'), 'data_access_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_data_access_logs_timestamp'), 'data_access_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_data_access_logs_user_id'), 'data_access_logs', ['user_id'], unique=False)
    op.create_table('data_scope_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('auto_filter_customers', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_warehouses', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_branches', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_sales', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_inventory', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_transactions', sa.Boolean(), nullable=True),
    sa.Column('include_subordinates', sa.Boolean(), nullable=True),
    sa.Column('custom_conditions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_data_scope_templates_id'), 'data_scope_templates', ['id'], unique=False)
    op.create_table('user_branches',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'branch_id')
    )
    op.create_table('user_data_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('auto_filter_customers', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_warehouses', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_branches', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_sales', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_inventory', sa.Boolean(), nullable=True),
    sa.Column('auto_filter_transactions', sa.Boolean(), nullable=True),
    sa.Column('include_subordinates', sa.Boolean(), nullable=True),
    sa.Column('custom_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_scopes_id'), 'user_data_scopes', ['id'], unique=False)
    op.create_index(op.f('ix_user_data_scopes_user_id'), 'user_data_scopes', ['user_id'], unique=True)
    op.create_table('user_warehouses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'warehouse_id')
    )
    op.create_table('user_customers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'customer_id')
    )
    op.create_index(op.f('ix_account_lockouts_id'), 'account_lockouts', ['id'], unique=False)
    op.drop_constraint('email_verification_tokens_token_key', 'email_verification_tokens', type_='unique')
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_mfa_verifications_id'), 'mfa_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_password_history_id'), 'password_history', ['id'], unique=False)
    op.drop_constraint('password_reset_tokens_token_key', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.drop_constraint('token_blacklist_token_key', 'token_blacklist', type_='unique')
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_trusted_devices_id'), 'trusted_devices', ['id'], unique=False)
    op.drop_constraint('user_mfa_user_id_key', 'user_mfa', type_='unique')
    op.create_index(op.f('ix_user_mfa_id'), 'user_mfa', ['id'], unique=False)
    op.drop_constraint('user_sessions_session_token_key', 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_unique_constraint(None, 'user_sessions', ['refresh_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.create_unique_constraint('user_sessions_session_token_key', 'user_sessions', ['session_token'])
    op.drop_index(op.f('ix_user_mfa_id'), table_name='user_mfa')
    op.create_unique_constraint('user_mfa_user_id_key', 'user_mfa', ['user_id'])
    op.drop_index(op.f('ix_trusted_devices_id'), table_name='trusted_devices')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.create_unique_constraint('token_blacklist_token_key', 'token_blacklist', ['token'])
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    op.alter_column('permissions', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.create_unique_constraint('password_reset_tokens_token_key', 'password_reset_tokens', ['token'])
    op.drop_index(op.f('ix_password_history_id'), table_name='password_history')
    op.drop_index(op.f('ix_mfa_verifications_id'), table_name='mfa_verifications')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.create_unique_constraint('email_verification_tokens_token_key', 'email_verification_tokens', ['token'])
    op.drop_index(op.f('ix_account_lockouts_id'), table_name='account_lockouts')
    op.drop_table('user_customers')
    op.drop_table('user_warehouses')
    op.drop_index(op.f('ix_user_data_scopes_user_id'), table_name='user_data_scopes')
    op.drop_index(op.f('ix_user_data_scopes_id'), table_name='user_data_scopes')
    op.drop_table('user_data_scopes')
    op.drop_table('user_branches')
    op.drop_index(op.f('ix_data_scope_templates_id'), table_name='data_scope_templates')
    op.drop_table('data_scope_templates')
    op.drop_index(op.f('ix_data_access_logs_user_id'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_timestamp'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_resource_type'), table_name='data_access_logs')
    op.drop_index(op.f('ix_data_access_logs_id'), table_name='data_access_logs')
    op.drop_table('data_access_logs')
    # ### end Alembic commands ### 