"""add_inventory_management_system

Revision ID: 8b5fc7e6bb8a
Revises: 9d2d52e3d8a3
Create Date: 2025-07-02 20:38:27.695272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5fc7e6bb8a'
down_revision = '9d2d52e3d8a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 