"""Add AI Assistant and WhatsApp models

Revision ID: 8c876ecf042a
Revises: 1d15a8abe0f8
Create Date: 2025-07-06 18:19:39.013277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c876ecf042a'
down_revision = '1d15a8abe0f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_auto_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_auto_responses_id'), 'whatsapp_auto_responses', ['id'], unique=False)
    op.create_table('whatsapp_broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.String(), nullable=True),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_broadcasts_broadcast_id'), 'whatsapp_broadcasts', ['broadcast_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_broadcasts_id'), 'whatsapp_broadcasts', ['id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('api_response', sa.JSON(), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_id'), 'whatsapp_messages', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_phone_number'), 'whatsapp_messages', ['phone_number'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_whatsapp_message_id'), 'whatsapp_messages', ['whatsapp_message_id'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_id'), 'ai_conversations', ['id'], unique=False)
    op.create_table('ai_generated_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('order_items', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generated_orders_id'), 'ai_generated_orders', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generated_orders_order_number'), 'ai_generated_orders', ['order_number'], unique=True)
    op.create_table('ai_support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_support_tickets_id'), 'ai_support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_ai_support_tickets_ticket_number'), 'ai_support_tickets', ['ticket_number'], unique=True)
    op.create_table('ai_conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('is_from_customer', sa.Boolean(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_messages_id'), 'ai_conversation_messages', ['id'], unique=False)
    op.drop_index('idx_money_transfers_datetime', table_name='money_transfers')
    op.drop_index('idx_money_transfers_platform', table_name='money_transfers')
    op.drop_index('idx_money_transfers_salesperson', table_name='money_transfers')
    op.drop_index('idx_money_transfers_status', table_name='money_transfers')
    op.drop_index('idx_money_transfers_suspicious', table_name='money_transfers')
    op.create_index(op.f('ix_money_transfers_id'), 'money_transfers', ['id'], unique=False)
    op.drop_constraint('transfer_platforms_platform_code_key', 'transfer_platforms', type_='unique')
    op.drop_constraint('transfer_platforms_platform_name_key', 'transfer_platforms', type_='unique')
    op.create_index(op.f('ix_transfer_platforms_id'), 'transfer_platforms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_platforms_id'), table_name='transfer_platforms')
    op.create_unique_constraint('transfer_platforms_platform_name_key', 'transfer_platforms', ['platform_name'])
    op.create_unique_constraint('transfer_platforms_platform_code_key', 'transfer_platforms', ['platform_code'])
    op.drop_index(op.f('ix_money_transfers_id'), table_name='money_transfers')
    op.create_index('idx_money_transfers_suspicious', 'money_transfers', ['is_suspicious'], unique=False)
    op.create_index('idx_money_transfers_status', 'money_transfers', ['status'], unique=False)
    op.create_index('idx_money_transfers_salesperson', 'money_transfers', ['salesperson_id'], unique=False)
    op.create_index('idx_money_transfers_platform', 'money_transfers', ['transfer_platform'], unique=False)
    op.create_index('idx_money_transfers_datetime', 'money_transfers', ['transfer_datetime'], unique=False)
    op.drop_index(op.f('ix_ai_conversation_messages_id'), table_name='ai_conversation_messages')
    op.drop_table('ai_conversation_messages')
    op.drop_index(op.f('ix_ai_support_tickets_ticket_number'), table_name='ai_support_tickets')
    op.drop_index(op.f('ix_ai_support_tickets_id'), table_name='ai_support_tickets')
    op.drop_table('ai_support_tickets')
    op.drop_index(op.f('ix_ai_generated_orders_order_number'), table_name='ai_generated_orders')
    op.drop_index(op.f('ix_ai_generated_orders_id'), table_name='ai_generated_orders')
    op.drop_table('ai_generated_orders')
    op.drop_index(op.f('ix_ai_conversations_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_whatsapp_messages_whatsapp_message_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_phone_number'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_broadcasts_id'), table_name='whatsapp_broadcasts')
    op.drop_index(op.f('ix_whatsapp_broadcasts_broadcast_id'), table_name='whatsapp_broadcasts')
    op.drop_table('whatsapp_broadcasts')
    op.drop_index(op.f('ix_whatsapp_auto_responses_id'), table_name='whatsapp_auto_responses')
    op.drop_table('whatsapp_auto_responses')
    # ### end Alembic commands ### 