"""Add migration management models

Revision ID: a8bb18ce3f72
Revises: f2c9b7d94700
Create Date: 2025-06-26 00:06:18.047974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bb18ce3f72'
down_revision = 'f2c9b7d94700'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['item_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_categories_code'), 'item_categories', ['code'], unique=True)
    op.create_index(op.f('ix_item_categories_id'), 'item_categories', ['id'], unique=False)
    op.create_table('migration_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('address_ar', sa.Text(), nullable=True),
    sa.Column('address_en', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.Enum('IQD', 'USD', 'RMB', name='currencyenum'), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('outstanding_payable', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('zoho_vendor_id', sa.String(length=100), nullable=True),
    sa.Column('zoho_last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vendor_zoho', 'migration_vendors', ['zoho_vendor_id'], unique=False)
    op.create_index(op.f('ix_migration_vendors_code'), 'migration_vendors', ['code'], unique=True)
    op.create_index(op.f('ix_migration_vendors_email'), 'migration_vendors', ['email'], unique=False)
    op.create_index(op.f('ix_migration_vendors_id'), 'migration_vendors', ['id'], unique=False)
    op.create_index(op.f('ix_migration_vendors_zoho_vendor_id'), 'migration_vendors', ['zoho_vendor_id'], unique=False)
    op.create_table('migration_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'REQUIRES_REVIEW', name='migrationstatusenum'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_entities', sa.Integer(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('successful_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('migration_config', sa.Text(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_batches_batch_number'), 'migration_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_migration_batches_id'), 'migration_batches', ['id'], unique=False)
    op.create_table('migration_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('cost_price_usd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('cost_price_iqd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('selling_price_usd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('selling_price_iqd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('track_inventory', sa.Boolean(), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reorder_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_serialized', sa.Boolean(), nullable=True),
    sa.Column('is_batch_tracked', sa.Boolean(), nullable=True),
    sa.Column('zoho_item_id', sa.String(length=100), nullable=True),
    sa.Column('zoho_last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_brand_model', 'migration_items', ['brand', 'model'], unique=False)
    op.create_index('idx_item_category', 'migration_items', ['category_id'], unique=False)
    op.create_index('idx_item_zoho', 'migration_items', ['zoho_item_id'], unique=False)
    op.create_index(op.f('ix_migration_items_code'), 'migration_items', ['code'], unique=True)
    op.create_index(op.f('ix_migration_items_id'), 'migration_items', ['id'], unique=False)
    op.create_index(op.f('ix_migration_items_zoho_item_id'), 'migration_items', ['zoho_item_id'], unique=False)
    op.create_table('price_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('currency', sa.Enum('IQD', 'USD', 'RMB', name='currencyenum'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('zoho_price_list_id', sa.String(length=100), nullable=True),
    sa.Column('zoho_last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_lists_code'), 'price_lists', ['code'], unique=True)
    op.create_index(op.f('ix_price_lists_id'), 'price_lists', ['id'], unique=False)
    op.create_index(op.f('ix_price_lists_zoho_price_list_id'), 'price_lists', ['zoho_price_list_id'], unique=False)
    op.create_table('migration_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('address_ar', sa.Text(), nullable=True),
    sa.Column('address_en', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.Enum('IQD', 'USD', 'RMB', name='currencyenum'), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('price_list_id', sa.Integer(), nullable=True),
    sa.Column('salesperson_id', sa.Integer(), nullable=True),
    sa.Column('assigned_region', sa.String(length=100), nullable=True),
    sa.Column('outstanding_receivable', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('zoho_customer_id', sa.String(length=100), nullable=True),
    sa.Column('zoho_deposit_account', sa.String(length=255), nullable=True),
    sa.Column('zoho_last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.ForeignKeyConstraint(['salesperson_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_region', 'migration_customers', ['region'], unique=False)
    op.create_index('idx_customer_salesperson', 'migration_customers', ['salesperson_id'], unique=False)
    op.create_index('idx_customer_zoho', 'migration_customers', ['zoho_customer_id'], unique=False)
    op.create_index(op.f('ix_migration_customers_code'), 'migration_customers', ['code'], unique=True)
    op.create_index(op.f('ix_migration_customers_email'), 'migration_customers', ['email'], unique=False)
    op.create_index(op.f('ix_migration_customers_id'), 'migration_customers', ['id'], unique=False)
    op.create_index(op.f('ix_migration_customers_zoho_customer_id'), 'migration_customers', ['zoho_customer_id'], unique=False)
    op.create_table('migration_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_data', sa.Text(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'REQUIRES_REVIEW', name='migrationstatusenum'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=True),
    sa.Column('manual_review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['migration_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_migration_record_batch_entity', 'migration_records', ['batch_id', 'entity_type'], unique=False)
    op.create_index('idx_migration_record_entity_source', 'migration_records', ['entity_type', 'source_id'], unique=False)
    op.create_index('idx_migration_record_status', 'migration_records', ['status'], unique=False)
    op.create_index(op.f('ix_migration_records_id'), 'migration_records', ['id'], unique=False)
    op.create_table('migration_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('last_cost', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reorder_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('max_stock_level', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('last_movement_date', sa.DateTime(), nullable=True),
    sa.Column('last_movement_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['migration_items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_item', 'migration_stock', ['item_id'], unique=False)
    op.create_index('idx_stock_item_warehouse', 'migration_stock', ['item_id', 'warehouse_id'], unique=False)
    op.create_index('idx_stock_warehouse', 'migration_stock', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_migration_stock_id'), 'migration_stock', ['id'], unique=False)
    op.create_table('price_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('minimum_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['migration_items.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_list_item', 'price_list_items', ['price_list_id', 'item_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_id'), 'price_list_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_list_items_id'), table_name='price_list_items')
    op.drop_index('idx_price_list_item', table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_index(op.f('ix_migration_stock_id'), table_name='migration_stock')
    op.drop_index('idx_stock_warehouse', table_name='migration_stock')
    op.drop_index('idx_stock_item_warehouse', table_name='migration_stock')
    op.drop_index('idx_stock_item', table_name='migration_stock')
    op.drop_table('migration_stock')
    op.drop_index(op.f('ix_migration_records_id'), table_name='migration_records')
    op.drop_index('idx_migration_record_status', table_name='migration_records')
    op.drop_index('idx_migration_record_entity_source', table_name='migration_records')
    op.drop_index('idx_migration_record_batch_entity', table_name='migration_records')
    op.drop_table('migration_records')
    op.drop_index(op.f('ix_migration_customers_zoho_customer_id'), table_name='migration_customers')
    op.drop_index(op.f('ix_migration_customers_id'), table_name='migration_customers')
    op.drop_index(op.f('ix_migration_customers_email'), table_name='migration_customers')
    op.drop_index(op.f('ix_migration_customers_code'), table_name='migration_customers')
    op.drop_index('idx_customer_zoho', table_name='migration_customers')
    op.drop_index('idx_customer_salesperson', table_name='migration_customers')
    op.drop_index('idx_customer_region', table_name='migration_customers')
    op.drop_table('migration_customers')
    op.drop_index(op.f('ix_price_lists_zoho_price_list_id'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_id'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_code'), table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_migration_items_zoho_item_id'), table_name='migration_items')
    op.drop_index(op.f('ix_migration_items_id'), table_name='migration_items')
    op.drop_index(op.f('ix_migration_items_code'), table_name='migration_items')
    op.drop_index('idx_item_zoho', table_name='migration_items')
    op.drop_index('idx_item_category', table_name='migration_items')
    op.drop_index('idx_item_brand_model', table_name='migration_items')
    op.drop_table('migration_items')
    op.drop_index(op.f('ix_migration_batches_id'), table_name='migration_batches')
    op.drop_index(op.f('ix_migration_batches_batch_number'), table_name='migration_batches')
    op.drop_table('migration_batches')
    op.drop_index(op.f('ix_migration_vendors_zoho_vendor_id'), table_name='migration_vendors')
    op.drop_index(op.f('ix_migration_vendors_id'), table_name='migration_vendors')
    op.drop_index(op.f('ix_migration_vendors_email'), table_name='migration_vendors')
    op.drop_index(op.f('ix_migration_vendors_code'), table_name='migration_vendors')
    op.drop_index('idx_vendor_zoho', table_name='migration_vendors')
    op.drop_table('migration_vendors')
    op.drop_index(op.f('ix_item_categories_id'), table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_code'), table_name='item_categories')
    op.drop_table('item_categories')
    # ### end Alembic commands ### 