"""add customer salesperson currency and portal language fields

Revision ID: cc38b931b533
Revises: a8bb18ce3f72
Create Date: 2025-06-26 22:38:13.950992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc38b931b533'
down_revision = 'a8bb18ce3f72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('customers', sa.Column('portal_language', sa.String(length=5), nullable=True))
    op.add_column('customers', sa.Column('salesperson_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'users', ['salesperson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'salesperson_id')
    op.drop_column('customers', 'portal_language')
    op.drop_column('customers', 'currency')
    # ### end Alembic commands ### 