"""Add cash flow management system

Revision ID: f2c9b7d94700
Revises: 1be42b77e23f
Create Date: 2025-06-25 23:14:52.817003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c9b7d94700'
down_revision = '1be42b77e23f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('box_type', sa.Enum('SALESPERSON', 'BRANCH', 'MAIN', 'PETTY_CASH', name='cashboxtypeenum'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance_iqd_cash', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('balance_iqd_digital', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('balance_usd_cash', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('balance_usd_digital', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('balance_rmb_cash', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('balance_rmb_digital', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('last_transaction_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_boxes_code'), 'cash_boxes', ['code'], unique=True)
    op.create_index(op.f('ix_cash_boxes_id'), 'cash_boxes', ['id'], unique=False)
    op.create_table('cash_flow_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('summary_date', sa.DateTime(), nullable=False),
    sa.Column('summary_type', sa.String(length=20), nullable=False),
    sa.Column('total_receipts_iqd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_payments_iqd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_receipts_usd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_payments_usd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_receipts_rmb', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_payments_rmb', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('net_flow_iqd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('net_flow_usd', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('net_flow_rmb', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('total_transfers_sent', sa.Integer(), nullable=True),
    sa.Column('total_transfers_received', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_summaries_id'), 'cash_flow_summaries', ['id'], unique=False)
    op.create_table('salesperson_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Enum('KARBALA', 'NAJAF', 'BABEL', 'BAGHDAD', 'BASRA', 'MOSUL', 'ERBIL', 'DUHOK', 'SULAYMANIYAH', 'KIRKUK', 'ANBAR', 'DIYALA', 'SALAHUDDIN', 'WASIT', 'QADISIYYAH', 'MUTHANNA', 'DHI_QAR', 'MAYSAN', name='regionenum'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salesperson_regions_id'), 'salesperson_regions', ['id'], unique=False)
    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_number', sa.String(length=100), nullable=False),
    sa.Column('cash_box_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'DIGITAL', 'BANK_TRANSFER', 'CHECK', name='cashpaymentmethodenum'), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('region', sa.Enum('KARBALA', 'NAJAF', 'BABEL', 'BAGHDAD', 'BASRA', 'MOSUL', 'ERBIL', 'DUHOK', 'SULAYMANIYAH', 'KIRKUK', 'ANBAR', 'DIYALA', 'SALAHUDDIN', 'WASIT', 'QADISIYYAH', 'MUTHANNA', 'DHI_QAR', 'MAYSAN', name='regionenum'), nullable=True),
    sa.Column('location_details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cash_box_id'], ['cash_boxes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_transactions_id'), 'cash_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_cash_transactions_transaction_number'), 'cash_transactions', ['transaction_number'], unique=True)
    op.create_table('cash_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_number', sa.String(length=100), nullable=False),
    sa.Column('from_cash_box_id', sa.Integer(), nullable=False),
    sa.Column('to_cash_box_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'DIGITAL', 'BANK_TRANSFER', 'CHECK', name='cashpaymentmethodenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'RECEIVED', 'REJECTED', 'CANCELLED', name='transferstatusenum'), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('transfer_reason', sa.String(length=500), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('requested_date', sa.DateTime(), nullable=False),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('transfer_receipt_url', sa.String(length=500), nullable=True),
    sa.Column('paper_attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_cash_box_id'], ['cash_boxes.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_cash_box_id'], ['cash_boxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_transfers_id'), 'cash_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_cash_transfers_transfer_number'), 'cash_transfers', ['transfer_number'], unique=True)
    op.add_column('branches', sa.Column('name_ar', sa.String(length=100), nullable=True))
    op.add_column('branches', sa.Column('name_en', sa.String(length=100), nullable=True))
    op.add_column('branches', sa.Column('branch_code', sa.String(length=20), nullable=True))
    op.add_column('branches', sa.Column('branch_type', sa.String(length=50), nullable=True))
    op.add_column('branches', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Update existing branches to be active
    op.execute("UPDATE branches SET is_active = true WHERE is_active IS NULL")
    # Now make it NOT NULL
    op.alter_column('branches', 'is_active', nullable=False)
    op.add_column('branches', sa.Column('description_ar', sa.Text(), nullable=True))
    op.add_column('branches', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('branches', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('branches', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('branches', sa.Column('address_ar', sa.Text(), nullable=True))
    op.add_column('branches', sa.Column('address_en', sa.Text(), nullable=True))
    op.add_column('branches', sa.Column('created_at', sa.DateTime(), nullable=True))
    # Update existing branches with current timestamp
    op.execute("UPDATE branches SET created_at = NOW() WHERE created_at IS NULL")
    # Now make it NOT NULL
    op.alter_column('branches', 'created_at', nullable=False)
    op.add_column('branches', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_branches_branch_code'), 'branches', ['branch_code'], unique=True)
    op.add_column('users', sa.Column('employee_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_salesperson', sa.Boolean(), nullable=True))
    # Update existing users to be not salespeople by default
    op.execute("UPDATE users SET is_salesperson = false WHERE is_salesperson IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'is_salesperson', nullable=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Update existing users to be active
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'is_active', nullable=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # Update existing users with current timestamp
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'created_at', nullable=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_salesperson')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'employee_code')
    op.drop_index(op.f('ix_branches_branch_code'), table_name='branches')
    op.drop_column('branches', 'updated_at')
    op.drop_column('branches', 'created_at')
    op.drop_column('branches', 'address_en')
    op.drop_column('branches', 'address_ar')
    op.drop_column('branches', 'email')
    op.drop_column('branches', 'phone')
    op.drop_column('branches', 'description_en')
    op.drop_column('branches', 'description_ar')
    op.drop_column('branches', 'is_active')
    op.drop_column('branches', 'branch_type')
    op.drop_column('branches', 'branch_code')
    op.drop_column('branches', 'name_en')
    op.drop_column('branches', 'name_ar')
    op.drop_index(op.f('ix_cash_transfers_transfer_number'), table_name='cash_transfers')
    op.drop_index(op.f('ix_cash_transfers_id'), table_name='cash_transfers')
    op.drop_table('cash_transfers')
    op.drop_index(op.f('ix_cash_transactions_transaction_number'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_id'), table_name='cash_transactions')
    op.drop_table('cash_transactions')
    op.drop_index(op.f('ix_salesperson_regions_id'), table_name='salesperson_regions')
    op.drop_table('salesperson_regions')
    op.drop_index(op.f('ix_cash_flow_summaries_id'), table_name='cash_flow_summaries')
    op.drop_table('cash_flow_summaries')
    op.drop_index(op.f('ix_cash_boxes_id'), table_name='cash_boxes')
    op.drop_index(op.f('ix_cash_boxes_code'), table_name='cash_boxes')
    op.drop_table('cash_boxes')
    # ### end Alembic commands ### 